name: Publish
description: Publish artifacts online

inputs:
  isRelease:
    type: boolean
    default: false
  publish:
    type: boolean
    default: true

runs:
  using: "composite"
  steps:

  - name: Install Apptainer
    uses: eWaterCycle/setup-apptainer@v2
    with:
      apptainer-version: 1.2.5

  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      pattern: packages-*
      merge-multiple: true
      path: ${{ github.workspace }}/packages

  - name: Download Prerequisites
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
      chmod u+x ./update-release

  - name: Package Examples
    shell: bash
    run: |
      set -ex
      cd ./examples
      ./package-examples -v ${{ env.dissolveVersion }}

  - name: Publish on GitHub (Release)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'true' }}
    shell: bash
    run: |
      echo "Release tag will be: ${{ env.dissolveVersion }}"
      echo "Release name will be: ${{ env.dissolveVersion }}"
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/dissolve -t ${{ env.dissolveVersion }} -n "${{ env.dissolveVersion }}" -f ReleaseNotes.md packages/* examples/*.zip examples/*.tar.gz

  - name: Publish on GitHub (Continuous)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'false' }}
    shell: bash
    run: |
      echo "Release tag will be: continuous"
      echo "Release name will be: 'Continuous (${{ env.dissolveVersion }} @ ${{ env.dissolveShortHash }})'"
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/dissolve -t continuous -p -e -u -n "Continuous (${{ env.dissolveVersion }} @ ${{ env.dissolveShortHash }})" -b "Continuous release from \`develop\` branch @ ${{ env.dissolveShortHash }}. Built $(date)." packages/*

  - name: Publish on Harbor (Release)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'true' }}
    shell: bash
    run: |
      echo "Release tag will be: latest"
      apptainer remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      apptainer push packages/dissolve-gui-${{ env.dissolveVersion }}.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/dissolve:latest

  - name: Publish on Harbor (Continuous)
    if: ${{ inputs.publish == 'true' && inputs.isRelease == 'false' }}
    shell: bash
    run: |
      echo "Release tag will be: continuous"
      apptainer remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      apptainer push packages/dissolve-gui-${{ env.dissolveVersion }}.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/dissolve:continuous
