name: Update Release Info
description: List releases and update website info

inputs:
  repository:
    type: string
    default: disorderedmaterials/dissolve
  createPR:
    type: boolean
    default: true
  releaseVersion:
    type: string

runs:
  using: "composite"
  steps:

  - name: Checkout Develop
    uses: actions/checkout@v4
    with:
      ref: develop

  - name: Update Release Information
    shell: bash
    run: |
      # Set release version to ours
      ./changeversion release -s ${{ inputs.releaseVersion }}

  - name: Create Update PR
    if: ${{ inputs.createPR == 'true' }}
    uses: peter-evans/create-pull-request@v4
    with:
      base: develop
      add-paths: |
        README.md
        web/main.toml
      commit-message: Update release version info.
      delete-branch: true
      branch: automation/update-current-release-to-${{ inputs.releaseVersion }}
      title: Update website release info (v${{ inputs.releaseVersion }})
      reviewers: trisyoungs
