#!/bin/bash

# Script to build Dissolve GUI (and serial) versions on OSX systems.
# Intended to be called as a job within GitHub Actions.

#
# Configuration
#
# -- Enforce verbosity for commands and exit on first failure
set -ev

#
# Install Prerequisites
#
# -- General
brew update
brew install bison ftgl ninja
# -- Qt
brew install qt5
QTVER=`ls -d /usr/local/Cellar/qt/* | sed "s/.*\(5\.[0-9][0-9]\.[0-9]\)/\1/g"`
export Qt5_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5
export Qt5Core_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Core
export Qt5Widgets_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Widgets
export Qt5PrintSupport_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5PrintSupport
export Qt5Gui_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Gui
Qt5_ROOT=/usr/local/Cellar/qt/${QTVER}

#
# Build
#
mkdir build
cd build
cmake -G "Ninja" -DGUI:bool=true ../
ninja
cd ../
