name: Pull Request
description: Pull request

on:
  pull_request:
    branches:
    - '*'
    paths:
    - 'develop.ps1'

jobs:

  Checkout:
    uses: "./.github/workflows/_checkout.yml"
    with:
      checkoutRef: ${{ github.event.pull_request.head.sha }}

  QC:
    needs: [Checkout]
    uses: "./.github/workflows/_qc.yml"
    with:
      nixHash: ${{ needs.Checkout.outputs.nixHash }}

  MsvcDev:
    needs: [Checkout]
    uses: "./.github/workflows/msvcDev.yml"
    with:
      qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
      antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
