#!/bin/bash

# Single argument expected - the name of the Module with correct capitalisation
if [ "$#" -eq "1" ]
then
  NAME=$1
else
  echo "Usage:  renamemodule <name>"
  echo "	<name> is the new name of the module with correct capitalisation (e.g. AtomShake, Energy, MD...)"
  exit 1
fi

LCASE=`echo $NAME | tr '[:upper:]' '[:lower:]'`
UCASE=`echo $NAME | tr '[:lower:]' '[:upper:]'`

echo "New Module Name = $NAME"
echo "Lowercased = $LCASE"
echo "Uppercased = $UCASE"

echo "Moving main header..."
mv -v skeleton.h ${LCASE}.h

echo "Changing boilerplate in main header..."
sed -i "s/SKELETON/${UCASE}/g" ${LCASE}.h gui/modulewidget.h

echo "Changing name in definition..."
sed -i "s/Skeleton/${NAME}/g" definition.cpp

echo "Renaming class..."
sed -i "s/SkeletonModule/${NAME}Module/g" *.cpp ${LCASE}.h gui/*.cpp gui/modulewidget.h gui/modulewidget.ui

echo "Adjusting include / header paths..."
sed -i "s/skeleton/${LCASE}/g" *.cpp ${LCASE}.h gui/modulewidget.h gui/*.cpp

echo "Adjusting makefiles..."
sed -i "s/skeleton/${LCASE}/g" CMakeLists.txt gui/CMakeLists.txt

echo "Adjusting header text..."
sed -i "s/Skeleton Module/${NAME} Module/g" *.cpp ${LCASE}.h gui/*.cpp gui/modulewidget.h
