#!/usr/bin/env bash

# Change the version of the source code to the supplied value

# Day Suffix Function
DaySuffix() {
  case $(date +%-d) in
    1|21|31) echo "st";;
    2|22)    echo "nd";;
    3|23)    echo "rd";;
    *)       echo "th";;
  esac
}

# Retrieve the authoritative code version from src/main/version.cpp
GetAuthoritativeVersion() {
  echo $(grep '#define DISSOLVEVERSION' src/main/version.cpp | sed -e 's/#define DISSOLVEVERSION "\([0-9a-z\.]\+\).*"/\1/g')
}

# Set versions in build files
SetCodeVersion() {
  # Must have new version string as argument
  if [ $# == 0 ]
  then
    echo "Must pass version string as argument to SetWebReleaseInfo()."
    exit 1
  fi

  # Program (main/version.h)
  sed -i -e "s/#define DISSOLVEVERSION \"[0-9\.]\+\(.*\)\"/#define DISSOLVEVERSION \"$1\"\1/g" src/main/version.cpp

  # Flake (flake.nix)
  sed -i -e "s/version = \".*\"/version = \"$1\"/" flake.nix

  # Root ./CMakeLists.txt
  PARTS=($(echo $1 | tr "." " "))
  MAJOR=${PARTS[0]}
  MINOR=${PARTS[1]}
  PATCH=${PARTS[2]}
  sed -i -e "s/set(VERSION_MAJOR \"\([0-9\.]\+\)\")/set(VERSION_MAJOR \"$MAJOR\")/g" -e "s/set(VERSION_MINOR \"\([0-9a-z\.]\+\)\")/set(VERSION_MINOR \"$MINOR\")/g" -e "s/set(VERSION_PATCH \"\([0-9a-z\.]\+\)\")/set(VERSION_PATCH \"$PATCH\")/g" CMakeLists.txt

}

# Get / check code versions in build files
GetCodeVersion() {
  # Program (main/version.h)
  MAIN_VERSION=$(grep '#define DISSOLVEVERSION' src/main/version.cpp | sed -e 's/#define DISSOLVEVERSION "\([0-9a-z\.]\+\).*"/\1/g')
  echo "         version.cpp : ${MAIN_VERSION}"

  if [[ ! "${MAIN_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "!!! Malformed version (or no version at all) found in version.cpp."
    return 1
  fi

  # Flake (flake.nix)
  FLAKE_VERSION=$(grep " version =" flake.nix | sed -e "s/\W*version = \"\(.*\)\";/\1/")
  echo "           flake.nix : ${FLAKE_VERSION}"

  # Root ./CMakeLists.txt
  CMAKE_MAJOR=$(grep 'set(VERSION_MAJOR' ./CMakeLists.txt | sed -e 's/set(VERSION_MAJOR \"\([0-9a-z\.]\+\)\")/\1/g')
  CMAKE_MINOR=$(grep 'set(VERSION_MINOR' ./CMakeLists.txt | sed -e 's/set(VERSION_MINOR \"\([0-9a-z\.]\+\)\")/\1/g')
  CMAKE_PATCH=$(grep 'set(VERSION_PATCH' ./CMakeLists.txt | sed -e 's/set(VERSION_PATCH \"\([0-9a-z\.]\+\)\")/\1/g')
  CMAKE_VERSION="${CMAKE_MAJOR}.${CMAKE_MINOR}.${CMAKE_PATCH}"
  echo "    ./CMakeLists.txt : ${CMAKE_VERSION}"

  # Check Version?
  if [ $# == 1 ]
  then
    if [ ${MAIN_VERSION} != "$1" ]
    then
      echo "!!! Version mismatch in version.cpp: ${MAIN_VERSION} != $1"
      return 1
    fi

    if [ ${FLAKE_VERSION} != "$1" ]
    then
      echo "!!! Version mismatch in flake.nix: ${FLAKE_VERSION} != $1"
      return 1
    fi

    if [ ${CMAKE_VERSION} != "$1" ]
    then
      echo "!!! Version mismatch in CMakeLists.cpp: ${CMAKE_VERSION} != $1"
      return 1
    fi
  fi

  return 0
}

# Set web release version and date
SetWebReleaseInfo() {
  # Must have new version string as argument
  if [ $# == 0 ]
  then
    echo "Must pass version string as argument to SetWebReleaseInfo()."
    exit 1
  fi

  # Get today's date, nicely formatted
  DAYSUFFIX=$(DaySuffix)
  TODAY=$(date "+%A %-d${DAYSUFFIX} %B %Y")

  # Set releaseVersion and releaseDat on Website (web/main.toml)
  sed -i -e "s/releaseVersion = \"[0-9\.]*\"/releaseVersion = \"$1\"/g" web/main.toml
  sed -i -e "s/releaseDate = \".*\"/releaseDate = \"${TODAY}\"/g" web/main.toml
}

# Get web release version and date
GetWebReleaseInfo() {
  # Release version on Website (web/main.toml)
  WEB_VERSION=$(grep 'releaseVersion' web/main.toml | sed -e 's/releaseVersion = "\([0-9\.]*\)"/\1/g')
  WEB_DATE=$(grep 'releaseDate' web/main.toml | sed -e 's/releaseDate = "\(.*\)"/\1/g')
  echo "           main.toml (Version) : ${WEB_VERSION}"
  echo "           main.toml    (Date) : ${WEB_DATE}"

  # Did we get a sensible version out of the file?
  if [[ ! "${WEB_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "!!! Malformed version (or no version at all) found in main.toml."
    return 1
  fi

  # Check Version?
  if [ $# == 1 ] && [ ${WEB_VERSION} != "$1" ]
  then
    echo "!!! Version mismatch in web/main.toml: ${WEB_VERSION} != $1"
    return 1
  fi

  return 0
}

# Set README.md version and date
SetReadMeInfo() {
  # Must have new version string as argument
  if [ $# == 0 ]
  then
    echo "Must pass version string as argument to SetReadMeInfo()."
    exit 1
  fi

  # Get today's date, nicely formatted
  DAYSUFFIX=$(DaySuffix)
  TODAY=$(date "+%A %-d${DAYSUFFIX} %B %Y")

  # Set the Last Release in the repository's root README.md
  sed -i -e "s/Last Release: [0-9\.]*, \(.*\)_/Last Release: $1, ${TODAY}_/g" README.md
}

# Get README.md version and date
GetReadMeInfo() {
  # Last Release in the repository's root README.md
  README_VERSION=$(grep 'Last Release:' README.md | sed -e 's/.*Release: \([0-9\.]*\),.*/\1/g')
  README_DATE=$(grep 'Last Release:' README.md | sed -e "s/.*Release: .*, \(.*\)_/\1/g")
  echo "           README.md (Version) : ${README_VERSION}"
  echo "           README.md    (Date) : ${README_DATE}"

  # Check Version?
  if [ $# == 1 ] && [ ${README_VERSION} != "$1" ]
  then
    echo "!!! Version mismatch in web/main.toml: ${WEB_VERSION} != $1"
    return 1
  fi

  return 0
}

ConsistencyCheck() {
  RETURN=0
  # Get authoritative source code version
  SRC_VERSION=$(GetAuthoritativeVersion)
  if ! GetWebReleaseInfo ${SRC_VERSION}; then RETURN=1; fi
  if ! GetCodeVersion ${SRC_VERSION}; then RETURN=1; fi
  exit $(( RETURN ))
}

PrintUsage() {
  echo "Usage:  $0 [-v] [-k] [-t] [-q] [-r X.Y.Z] [-s X.Y.Z]"
  echo "        -r  Explicitly set release version and date in README.md"
  echo "        -s  Set version explicitly to X.Y.Z"
  echo "        -v  Get authoritative code version (from src/main/version.cpp)"
  echo "        -x  Get authoritative code version (from src/main/version.cpp) with patch version set to a literal 'X'"
  echo "        -k  Check consistency of other files with current authoritative version"
  echo "        -q  Determine bumped version using git-cliff"
  echo "        -t  Determine type (major, minor, patch, or none) of bumped version using git-cliff"
  echo "        -b  Determine bumped version using git-cliff and set new authoritative version"
  echo "        -l  Generate ChangeLog.md containing unreleased changes since last major/minor/patch release"
  echo "        -L  Generate ChangeLog.md over the current branch history"
}

# Check for no args provided
if [ $# == 0 ]
then
  PrintUsage
  exit 1
fi

while getopts "r:s:vkqblLxt" opt
do
  case $opt in
    s) PARTS=($(echo $OPTARG | tr "." " "))
       MAJOR=${PARTS[0]}
       MINOR=${PARTS[1]}
       PATCH=${PARTS[2]}
       echo "Code and web version will be set explicitly to MAJOR=$MAJOR MINOR=$MINOR PATCH=$PATCH"
       SetCodeVersion $OPTARG
       SetWebReleaseInfo $OPTARG
       ConsistencyCheck
       ;;
    r) PARTS=($(echo $OPTARG | tr "." " "))
       MAJOR=${PARTS[0]}
       MINOR=${PARTS[1]}
       PATCH=${PARTS[2]}
       echo "Release version will be set explicitly to MAJOR=$MAJOR MINOR=$MINOR PATCH=$PATCH"
       SetReadMeInfo $OPTARG
       GetReadMeInfo
       ;;
    q) git cliff --bumped-version -u
       ;;
    b) CURRENT=$(GetAuthoritativeVersion)
       BUMPED=$(git cliff --bumped-version -u)
       if [ "${BUMPED}x" == "x" ]
       then
         echo "Error: Failed to auto-bump version."
         exit 1
       fi
       SetCodeVersion ${BUMPED}
       SetWebReleaseInfo ${BUMPED}
       echo "Version auto-bumped to ${BUMPED} (from ${CURRENT})"
       ;;
    l) git cliff --bump -u
       ;;
    L) git cliff --bump
       ;;
    v) GetAuthoritativeVersion
       exit 0
       ;;
    x) CURRENT=$(GetAuthoritativeVersion)
       PARTS=($(echo $CURRENT | tr "." " "))
       MAJOR=${PARTS[0]}
       MINOR=${PARTS[1]}
       echo "${MAJOR}.${MINOR}.X"
       exit 0
       ;;
    k) ConsistencyCheck
       ;;
    t) CURRENT=$(GetAuthoritativeVersion)
       CURRENT_PARTS=($(echo $CURRENT | tr "." " "))
       BUMPED=$(git cliff --bumped-version -u)
       BUMPED_PARTS=($(echo $BUMPED | tr "." " "))
       if [ "${CURRENT_PARTS[0]}" != "${BUMPED_PARTS[0]}" ]
       then
         echo "major"
       elif [ "${CURRENT_PARTS[1]}" != "${BUMPED_PARTS[1]}" ]
       then
         echo "minor"
       elif [ "${CURRENT_PARTS[2]}" != "${BUMPED_PARTS[2]}" ]
       then
         echo "patch"
       else
         echo "none"
       fi
       exit 0
       ;;
   \?) PrintUsage
       exit 1
       ;;
    *) echo "Error: Extra operands given."
       PrintUsage
       exit 1
       ;;
  esac
done

