#!/bin/bash

# Script to 'wrap' around git and update ChangeLog and version / date in file.

COMMITFILE="none"
COMMITMSG="none"
COMMITTYPE="none"
BUMP="false"
ALL="true"

# Parse CLI arguments / options
USAGE1="commit [-F <filename>] [-m <text>] [-p] [-b] [-o]"

while getopts "F:m:bpo" options; do
  case $options in
    F ) COMMITFILE=$OPTARG
	COMMITTYPE="file"
        echo "Using file "$COMMITFILE" for commit message.";;
    m ) COMMITMSG=$OPTARG
	COMMITTYPE="msg"
        echo "Using supplied text for commit message.";;
    b ) BUMP="true"
	echo "Version (patch) number will be bumped.";;
    o ) ALL="false"
	echo "Only specific changes will be committed.";;
    \? ) echo -e $USAGE1
         exit 1;;
    * ) echo -e $USAGE1
        exit 1;;
  esac
done

# Set up flags to pass
FLAGS=""
if [ "$ALL" = "true" ]
then
  FLAGS="$FLAGS -a"
fi

# Check that a commit type was given
if [ "$COMMITTYPE" = "none" ]
then
  echo "No commit message/file was given."
  exit 0
fi

# Bump version if requested
if [ "$BUMP" = "true" ]
then
  ./changeversion bump
else
  ./changeversion
fi

# Commit changes
if [ "$COMMITTYPE" = "file" ]
then
  git commit $FLAGS -F $COMMITFILE
fi
if [ "$COMMITTYPE" = "msg" ]
then
  git commit $FLAGS -m "$COMMITMSG"
fi

exit 0
