version = "1.8.0"

[pairPotentials]
range = 15.0
delta = 0.005
autoChargeSource = true
coulombTruncation = "Shifted"
shortRangeTruncation = "Shifted"
includeCoulomb = true

[graph]
name = "Root"
type = "Dissolve"
x = 0
y = 0

[graph.nodes]

[graph.nodes.Water]
name = "Water"
type = "Species"
x = 0
y = 0

[graph.nodes.Water.options]

[graph.nodes.Water.options.Species]

[graph.nodes.Water.options.Species.data]
name = "Water"

[[graph.nodes.Water.options.Species.data.atoms]]
index = 1
z = "O"
r = [
1.0,
2.0,
3.0,
]
charge = -0.82
[[graph.nodes.Water.options.Species.data.atoms]]
index = 2
z = "H"
r = [
4.0,
25.0,
nan,
]
charge = 0.42
[[graph.nodes.Water.options.Species.data.atoms]]
index = 3
z = "H"
r = [
7.0,
8.0,
9.0,
]
charge = 0.42



