name: Basic Setup
description: Set up environment variables

inputs:
  qtVersion:
    type: string
    default: 6.4.2
  nixVersion:
    type: string
    default: 2.4
  nixOSVersion:
    type: string
    default: 22.11
  hugoVersion:
    type: string
    default: "0.135.0"
  conanfile:
    type: string
    default: cmake/Modules/conan-dissolve.cmake

runs:
  using: "composite"
  steps:

    - name: Setup environment
      shell: bash
      run: |
        set -ex
        echo "qtVersion=${{ inputs.qtVersion }}" >> ${GITHUB_ENV}
        echo "nixVersion=${{ inputs.nixVersion }}" >> ${GITHUB_ENV}
        echo "nixOSVersion=${{ inputs.nixOSVersion }}" >> ${GITHUB_ENV}
        echo "hugoVersion=${{ inputs.hugoVersion }}" >> ${GITHUB_ENV}

    - name: Get package versions
      shell: bash
      run: |
        ANTLR_VERSION=$(cat ${{ inputs.conanfile }}  | sed -n -e 's%^.*antlr4-cppruntime/%%p')
        echo "antlrVersion=${ANTLR_VERSION}" >> ${GITHUB_ENV}

    - name: Install Dependencies (OSX)
      if: ${{ runner.os == 'macos' }}
      shell: bash
      run: brew install coreutils gawk gsl

    - name: Get nix hash
      shell: bash
      run: |
        set -ex
        NIX_HASH=`sha256sum flake.lock | gawk '{print $1}'`
        echo "Hash of nix files (flake.lock and flake.nix) is ${NIX_HASH}"
        echo "nixHash=${NIX_HASH}" >> ${GITHUB_ENV}

    - name: Get conan hash
      shell: bash
      run: |
        set -ex
        CONAN_HASH=`sha256sum ${{ inputs.conanfile }} | gawk '{print $1}'`
        echo "Hash of conanfile.txt is ${CONAN_HASH}"
        echo "conanHash=${CONAN_HASH}" >> ${GITHUB_ENV}
