#!/bin/bash

# Script to build Dissolve parallel version on Ubuntu-based systems.
# Intended to be called as a job within GitHub Actions.

#
# Configuration
#
# -- Enforce verbosity for commands and exit on first failure
set -ev

#
# Install Prerequisites
#
# -- General
sudo apt-get install bison ninja-build libopenmpi-dev openmpi-bin openmpi-common

#
# Build
#
mkdir build-parallel
cd build-parallel
cmake -G "Ninja" -DPARALLEL:bool=true ../
ninja
cd ../
