name: Set Short Hash

runs:
  using: "composite"
  steps:

  - name: Set Short Hash
    shell: bash
    run: |
      set -ex
      SHORT_HASH=$(git rev-parse --short HEAD)
      echo "Current short hash is ${shortHash}"
      sed -i "s/DISSOLVESHORTHASH \".*\"/DISSOLVESHORTHASH \"${shortHash}\"/g" src/main/version.cpp
      cat src/main/version.cpp
