name: Update Release Info
description: List releases and update website info

inputs:
  repository:
    type: string
    default: disorderedmaterials/dissolve
  createPR:
    type: boolean
    default: true
  releaseVersion:
    type: string

runs:
  using: "composite"
  steps:

  - name: Checkout Develop
    uses: actions/checkout@v4
    with:
      ref: develop

  - name: Update Version in README.md
    shell: bash
    run: |
      ./changeversion -r ${{ inputs.releaseVersion }}

  - name: Create Update PR
    uses: peter-evans/create-pull-request@v4
    with:
      base: develop
      add-paths: README.md
      commit-message: Update version in README.md
      delete-branch: true
      branch: automation/update-current-release-to-${{ inputs.releaseVersion }}
      title: [Latest Release] Update README.md release info (v${{ inputs.releaseVersion }})
      reviewers: trisyoungs
