name: Get Code Version
description: Obtain and export code version from source

runs:
  using: "composite"
  steps:

  - name: Grep Version
    shell: bash
    run: |
      set -ex
      DISSOLVE_VERSION=`grep "#define DISSOLVEVERSION" src/main/version.cpp | sed 's/.*\"\(.*\)\"/\1/g'`
      echo "Dissolve code version is ${DISSOLVE_VERSION}"
      DISSOLVE_MAJOR=`echo $DISSOLVE_VERSION | sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1/g"`
      DISSOLVE_MINOR=`echo $DISSOLVE_VERSION | sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/g"`
      DISSOLVE_PATCH=`echo $DISSOLVE_VERSION | sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\3/g"`
      echo "Dissolve major version is ${DISSOLVE_MAJOR}"
      echo "dissolveVersion=${DISSOLVE_VERSION}" >> ${GITHUB_ENV}
      echo "dissolveMajorVersion=${DISSOLVE_MAJOR}" >> ${GITHUB_ENV}
      echo "dissolveMinorVersion=${DISSOLVE_MINOR}" >> ${GITHUB_ENV}
      echo "dissolvePatchVersion=${DISSOLVE_PATCH}" >> ${GITHUB_ENV}
