jobs:
  - job: "release_linux_mpi"
    displayName: "Release MPI, CLI, Exe"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve-mpi"
  - job: "release_linux_mpi_image"
    displayName: "Release MPI, CLI, Singularity"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve-mpi"
          exportExe: false
          exportSingularity: true
  - job: "release_linux_gui"
    displayName: "Release GUI, Exe"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve-gui"
  - job: "release_linux_gui_image"
    displayName: "Release GUI, Singularity"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve-gui"
          exportExe: false
          exportSingularity: true
  - job: "release_linux"
    displayName: "Release CLI, Exe"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve"
  - job: "release_linux_image"
    displayName: "Release CLI, Singularity"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve"
          exportExe: false
          exportSingularity: true
  - job: "release_linux_threadless"
    displayName: "Release Threadless"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 1
      - template: set-short-hash.yml
      - template: build-linux.yml
        parameters:
          package: "dissolve-threadless"
