parameters:
  - name: extraflags
    default: ''
  - name: qtver
    default: 6.1.1
  - name: gui
    default: true
  - name: threading
    default: true

steps:
  - bash: |
      set -ex
      # -- General
      sudo apt-get update -q
      # FIXME: This is a debugging line that needs to be deleted before merging
      sudo apt install libxkbcommon-x11-0 libxcb-render0 libxcb-render-util0 libxcb-shape0 libxcb-randr0 libxcb-xfixes0 libxcb-xkb1 libxcb-sync1 libxcb-shm0 libxcb-icccm4 libxcb-keysyms1 libxcb-image0 libxcb-util1 libfontconfig
      sudo apt-get install antlr4 libfreetype6-dev libftgl-dev ninja-build python3-setuptools uuid uuid-dev
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      sudo pip3 install wheel
      sudo pip3 install conan
      # -- Qt
      sudo pip3 install aqtinstall
      aqt install --outputdir /tmp/qt ${{ parameters.qtver }} linux desktop -m qtcore qtgui qtwidgets qtopengl qtopenglwidgets
    displayName: 'Install Conan'
  - bash: |
      set -ex
      Qt6_DIR=/tmp/qt/${{ parameters.qtver }}/gcc_64/lib/cmake/Qt6
      QT_BASE_DIR=/tmp/qt/${{ parameters.qtver }}/gcc_64
      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
      mkdir build
      cd build
      conan install .. -s compiler.libcxx=libstdc++11 --build missing
      cmake -G "Ninja" -DMULTI_THREADING:bool=${{ parameters.threading }} -DGUI:bool=${{ parameters.gui }} -DBUILD_ANTLR_RUNTIME:bool=true ${{ parameters.extraflags }} ../
      ninja
    displayName: 'Build'
