parameters:
  - name: deploy
    default: false
    type: boolean
  - name: hugo_version
    default: '0.79.0'
  - name: web_dir_root
    default: 'github.com/disorderedmaterials/dissolve/edit/develop/web'
  - name: last_hash_url
    default: 'https://www.projectdissolve.com'

steps:
  - checkout: self
    submodules: true
  - bash: |
      git submodule update --init --recursive --depth 1
    displayName: 'Init Submodules'
  - bash: |
      set -ex
      wget https://github.com/gohugoio/hugo/releases/download/v${{ parameters.hugo_version }}/hugo_extended_${{ parameters.hugo_version }}_Linux-64bit.deb -O '$(Pipeline.Workspace)/hugo.deb'
      sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
    displayName: 'Download & Install Hugo (Extended Version)'
  - bash: |
      set -ex
      cd web
      npm install
      hugo
    displayName: 'Build Site'
  - bash: |
      set -ex
      # Remove language ('en') from 'Edit on GitHub' path links
      find web/public/docs/ -iname *.html -exec sed -i "s:${{ parameters.web_dir_root }}/content/en/docs/:${{ parameters.web_dir_root }}/content/docs/:g" {} +
      find web/public/examples/ -iname *.html -exec sed -i "s:${{ parameters.web_dir_root }}/content/en/examples/:${{ parameters.web_dir_root }}/content/examples/:g" {} +
    displayName: 'Rewrite Edit Links'
  - bash: |
      set -ex
      sudo npm install -g link-checker
      link-checker --disable-external web/public
    displayName: 'Check Links'
  - task: DownloadSecureFile@1
    name: privateKey
    inputs:
      secureFile: id_rsa_dd
    condition: eq('${{ parameters.deploy }}', true)
    displayName: 'Download Private Key'
  - task: DownloadSecureFile@1
    name: machineId
    inputs:
      secureFile: pd_hostkey
    condition: eq('${{ parameters.deploy }}', true)
    displayName: 'Download Host Fingerprint'
  - bash: |
      chmod 0600 $(privateKey.secureFilePath) $(machineId.secureFilePath)
      rsync -avz --delete -e "ssh -o UserKnownHostsFile=$(machineId.secureFilePath) -i $(privateKey.secureFilePath) -p 2212 -l doctordissolve" web/public/ 87.117.225.2:/home/www/www.projectdissolve.com/public_html/
    condition: eq('${{ parameters.deploy }}', true)
    displayName: 'SSH Deploy to Server'
