parameters:
  - name: gui
    default: true
  - name: threading
    default: true

steps:
  - bash: |
      set -ex
      # -- General
      sudo apt-get update -q
      sudo apt-get install curl gpg2
      curl -o install-nix-2.3.16 https://releases.nixos.org/nix/nix-2.3.16/install
      curl -o install-nix-2.3.16.asc https://releases.nixos.org/nix/nix-2.3.16/install.asc
      gpg2 --recv-keys B541D55301270E0BCF15CA5D8170B4726D7198DE
      gpg2 --verify ./install-nix-2.3.16.asc
      sh ./install-nix-2.3.16
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      nix build .
    displayName: 'Build'
