parameters:
  - name: extraflags
    default: ''
  - name: parallel
    type: string
    default: "false"
  - name: mac
    type: boolean
    default: false
  - name: nixName
    default: ''
    type: string

steps:
  - bash: |
      set -ex
      sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
      curl -L https://nixos.org/nix/install | sh
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update
    displayName: 'Install Prerequisites'
    condition: not(${{parameters.mac}})
  - bash: |
      set -ex
      sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update
    displayName: 'Install Mac Prerequisites'
    condition: ${{parameters.mac}}
  - bash: |
      set -ex
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use rprospero
      cd nix
      nix-build ${{parameters.nixName}}.nix --arg parallel ${{parameters.parallel}}
      cd ..
      nix-instantiate nix/${{parameters.nixName}}.nix --arg parallel ${{parameters.parallel}} | xargs nix-store -r | xargs nix-store -q --references | xargs tar czf tests/nix.tar.gz
      # tar czf tests/nix.tar.gz /nix/store/*
      # cp nix/result/bin/dissolve* tests/
    displayName: 'Build'
