parameters:
  - name: extraflags
    default: ''
  - name: parallel
    default: false

steps:
  - bash: |
      set -ex
      sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
      curl -L https://nixos.org/nix/install | sh
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use rprospero
      cd nix
      nix-build dissolve.nix --arg parallel ${{parameters.parallel}}
      cd ..
      nix-instantiate nix/dissolve.nix | xargs nix-store -r | xargs nix-store -q --references | xargs tar czf tests/nix.tar.gz
      cp nix/result/bin/dissolve* tests/
    displayName: 'Build'
