parameters:
  - name: extraflags
    default: ''
  - name: ppa
    default: 'beineri/opt-qt-5.13.2-bionic'
  - name: qtver
    default: 513

steps:
  - bash: |
      set -ex
      sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
      curl -L https://nixos.org/nix/install | sh
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
      nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
      nix-channel --update
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      source ~/.nix-profile/etc/profile.d/nix.sh
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use rprospero
      cd nix
      bash ./nix_build.sh
      cd ..
    displayName: 'Build'
