parameters:
  - name: qtver
    default: 6.1.1

steps:
  - script: |
      choco install -y zip innoextract
    displayName: 'Install Prerequisites'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      # Set paths
      $env:Qt6_DIR = "$(Build.BinariesDirectory)\Qt\${{ parameters.qtver }}\msvc2019_64"
      $env:PATH += ";$env:Qt6_DIR" + "\bin"
      echo $env:Qt6_DIR
      $env:MINGW_DIR = $env:Qt6_DIR
      $env:FREETYPE_DIR = "$(Build.BinariesDirectory)\freetype-install\bin"
      $env:FTGL_DIR = "$(Build.BinariesDirectory)\ftgl-install\bin"
      $env:ANTLR_DIR = $(Get-Location).path + "\build\antlr4runtime\src\antlr_runtime\dist\Release"
      $env:DISSOLVE_DIR = $(Get-Location).path + "\build\bin"
      # Run Inno Setup Compiler
      iscc.exe /O.\ .\ci\windows\dissolve-gui.iss
      $exe = Get-ChildItem  .\*.exe
      echo "Executable installer is "$exe.Name
      # Create Zip from Exe
      innoextract.exe $exe.Name -d $exe.BaseName
      mv "$($exe.BaseName)\app\bin\*" $exe.BaseName
      mv "$($exe.BaseName)\app" ./
      #rm -Force "$($exe.BaseName)\app"
      $zip = $exe.BaseName + ".zip"
      zip -r $zip $exe.BaseName
      # Collect artifacts
      mkdir packages
      mv $zip packages
      mv $exe.Name packages
    displayName: 'Create Packages'
