parameters:
  - name: mpi
    default: true
  - name: threading
    default: true
  - name: serial
    default: true
  - name: qtver
    default: 6.1.1

jobs:
  - job:
    condition: eq('${{ parameters.threading }}', true)
    displayName: 'Threads'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - bash: |
          set -ex
          sudo pip3 install aqtinstall
          sudo apt-get install libgl1-mesa-glx libopengl0 libegl1 libegl1-mesa
          aqt install --outputdir /tmp/qt ${{ parameters.qtver }} linux desktop -m qtcore qtgui qtwidgets qtopengl qtopenglwidgets
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-tests'
        displayName: 'Download Threaded Test Artifacts'
      - bash: |
          set -ex
          export LD_LIBRARY_PATH=/tmp/qt/${{ parameters.qtver }}/gcc_64/lib:$LD_LIBRARY_PATH
          mkdir build && cd build
          mv $(System.ArtifactsDirectory)/linux-tests/* ./
          chmod +x bin/*
          ctest -j2 --output-on-failure
        displayName: 'Run Serial System Tests'
  - job:
    condition: eq('${{ parameters.serial }}', true)
    displayName: 'Serial'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-tests-serial'
        displayName: 'Download Serial Test Artifacts'
      - bash: |
          set -ex
          mkdir build && cd build
          mv $(System.ArtifactsDirectory)/linux-tests-serial/* ./
          chmod +x bin/*
          ctest -j2 --output-on-failure
        displayName: 'Run Serial System Tests'
  - job:
    condition: eq('${{ parameters.mpi }}', true)
    displayName: 'MPI'
    timeoutInMinutes: 90
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - bash: |
          set -ex
          sudo apt-get update
          sudo apt-get install libopenmpi-dev openmpi-bin openmpi-common
        displayName: 'Install Prerequisites'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-tests-mpi'
        displayName: 'Download MPI Test Artifacts'
      - bash: |
          set -ex
          mkdir build && cd build
          mv $(System.ArtifactsDirectory)/linux-tests-mpi/* ./
          chmod +x bin/*
          ctest --output-on-failure
        displayName: 'Run MPI System Tests'
