add_library(
  nodes
  add.cpp
  add.h
  atomShake.cpp
  atomShake.h
  constants.h
  derivative.cpp
  derivative.h
  dissolve.cpp
  dissolve.h
  dotProduct.cpp
  dotProduct.h
  edge.cpp
  edge.h
  graph.cpp
  graph.h
  integrator.cpp
  integrator.h
  multiply.cpp
  multiply.h
  node.cpp
  node.h
  number.cpp
  number.h
  parameter.cpp
  parameter.h
  registry.cpp
  registry.h
  subtract.cpp
  subtract.h
  vec3Assembly.cpp
  vec3Assembly.h
  vec3Decomposition.cpp
  vec3Decomposition.h
)

target_include_directories(nodes PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(nodes PUBLIC base ${THREADING_LINK_LIBS})
