/*
	*** Interatomic Pair Potential
	*** src/classes/pairpotential.h
	Copyright T. Youngs 2012-2017

	This file is part of dUQ.

	dUQ is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	dUQ is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with dUQ.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef DUQ_PAIRPOTENTIAL_H
#define DUQ_PAIRPOTENTIAL_H

#include "base/xydata.h"
#include "templates/list.h"

// Forward Declarations
class AtomType;

// PairPotential Definition
class PairPotential : public ListItem<PairPotential>
{
	public:
	// Constructor
	PairPotential();
	// ShortRange Interaction Type enum
	enum ShortRangeType
	{
		NoShortRange,			/* No short-range dispersive forces */
		LennardJonesType,		/* Lennard-Jones 12-6 form */
		nShortRangeTypes		/* Number of short-range interaction types */
	};
	// Convert text string to ShortRangeType
	static ShortRangeType shortRangeType(const char* s);
	// Convert ShortRangeType to text string
	static const char* shortRangeType(ShortRangeType id);


	/*
	 * Potential Type
	 */
	private:
	// Short range type
	ShortRangeType shortRangeType_;
	// Whether charges should be included in the generated potential
	bool includeCharges_;
	
	public:
	// Set short-ranged type
	void setShortRangeType(ShortRangeType type);
	// Return short-ranged type
	ShortRangeType shortRangeType() const;


	/*
	 * Source Parameters
	 */
	private:
	// Original source AtomTypes
	AtomType* atomTypeI_, *atomTypeJ_;
	// Sigma value (determined from AtomTypes)
	double sigmaIJ_;
	// Epsilon value (determined from AtomTypes)
	double epsilonIJ_;
	// Charge on I (taken from AtomType)
	double chargeI_;
	// Charge on J (taken from AtomType)
	double chargeJ_;
	
	private:
	// Set XYData names from source AtomTypes
	void setXYDataNames();
	
	public:
	// Set source parameters from AtomTypes
	void setParameters(AtomType* typeI, AtomType* typeJ);
	// Set source AtomType pointers only
	void setAtomTypes(AtomType* typeI, AtomType* typeJ);
	// Return first AtomType name
	const char* atomTypeNameI() const;
	// Return second AtomType name
	const char* atomTypeNameJ() const;
	// Return first source AtomType
	AtomType* atomTypeI() const;
	// Return second source AtomType
	AtomType* atomTypeJ() const;
	// Set sigma
	void setSigmaIJ(double value);
	// Return sigma
	double sigmaIJ() const;
	// Set epsilon
	void setEpsilonIJ(double value);
	// Return epsilon
	double epsilonIJ() const;
	// Set charge I
	void setChargeI(double value);
	// Return charge I
	double chargeI() const;
	// Set charge J
	void setChargeJ(double value);
	// Return charge J
	double chargeJ() const;


	/*
	 * Tabulated Potential
	 */
	private:
	// Number of points to tabulate
	int nPoints_;
	// Maximum distance of potential
	double range_, rangeSquared_;
	// Distance between r-squared points in tabulated potentials
	double delta_, rDelta_;
	// Truncation width for LJ part of potential
	double truncationWidth_;
	// Tabulated original potential, calculated from AtomType parameters
	XYData uOriginal_;
	// Additional potential, generated by some means
	XYData uAdditional_;
	// Full potential (original plus additional), used in simulations
	XYData uFull_;
	// Tabulated derivative of full potential
	XYData dUFull_;
	
	private:
	// Regenerate derivative data
	void calculateDUFull();
	// Calculate full potential
	void calculateUFull();

	public:
	// Setup and perform initial generation of potential
	bool setup(double maxR, double truncationWidth, double delta, bool includeCharges);
	// (Re)generate original potential (uOriginal) from current parameters
	bool calculateUOriginal(bool recalculateUFull = true);
	// Return potential at specified r-squared
	double energyAtRSquared(double rSq);
	// Return analytic potential at specified r-squared
	double analyticEnergyAtRSquared(double rSq);
	// Return derivative of potential at specified r-squared
	double forceAtRSquared(double rSq);
	// Return full tabulated potential (original plus additional)
	XYData& uFull();
	// Return full tabulated derivative
	XYData& dUFull();
	// Return original potential (calculated from AtomType parameters)
	XYData& uOriginal();
	// Return additional potential (generated by some means)
	XYData& uAdditional();
	// Zero additional potential
	void resetUAdditional();


	/*
	 * File I/O
	 */
	public:
	// Save PairPotential data to specified file
	bool save(const char* filename);


	/*
	 * Parallel Comms
	 */
	public:
	// Broadcast data from Master to all Slaves
	bool broadcast(ProcessPool& procPool, const List<AtomType>& atomTypes);
};

#endif
