name: Quality Control

runs:
  using: "composite"
  steps:

  - name: Install Dependencies
    shell: bash
    run: |
      set -ex
      sudo apt-get update
      sudo apt-get install --yes clang-format-13 qt6-declarative-dev-tools
      pip install cmake_format==0.6.9

  - name: Check Conventional Commits
    # Ensure that the PR title fits the conventional commits framework
    shell: bash
    run: |
      set -ex
      TITLE="${{ github.event.pull_request.title }}"
      if [ -z "$TITLE" ]
      then
      TITLE=Continuous
      fi
      fi
      echo  | awk "/(Continuous)|(^feat:)|(^fix:)|(^doc:)|(^perf:)|(^refactor:)|(^style:)|(^test:)|(^chore:)|(^revert:)|(^build:)/" | grep .

  - name: C++ Formatting
    shell: bash
    run: |
      set -ex
      clang-format-13 --version
      find . -type f -regex '.*\.\(c\|cpp\|h\|hpp\|hui\)' -exec clang-format-13 -i {} +
      git diff
      git diff --quiet

  - name: CMake Formatting
    shell: bash
    run: |
      set -ex
      cmake-format --version
      find . -type f -name CMakeLists.txt -exec cmake-format -i '{}' \;
      git diff
      git diff --quiet

  - name: QML Formatting
    shell: bash
    run: |
      set -ex
      /usr/lib/qt6/bin/qmlformat --version
      find . -type f -regex '.*\.qml' -exec /usr/lib/qt6/bin/qmlformat -inw 4 '{}' \;
      git diff
      git diff --quiet

  - name: Copyright Year
    shell: bash
    run: |
      set -ex
      # Find all occurances of "YYYY Team Dissolve and contributors" and replace YYYY with the current year
      find . -type f -not -path '.git/*' -exec sed -ri "s/[0-9]{4} (Team Dissolve and contributors)/$(date +%Y) \1/g" {} +
      # Show the diff to give an indication of the issues in the CI log
      git diff
      # Run quiet diff to fail the job if any changes were made (see man git-diff)
      git diff --quiet
