name: Quality Control
description: Run quality control checks over the source code

inputs:
  nixHash:
    type: string
    required: true

runs:
  using: "composite"
  steps:

  - name: Install nix
    uses: "./.github/workflows/get-nix"
    with:
      target: ${{ inputs.target }}

  - name: Cache Nix Store
    uses: actions/cache@v4
    id: nix-cache
    with:
      path: /tmp/nixcache
      key: ${{ runner.os }}-${{ inputs.nixHash }}-nix-cache

  - name: Import Nix Store Cache
    if: "steps.nix-cache.outputs.cache-hit == 'true'"
    shell: bash
    run: |
      nix-store --import < /tmp/nixcache
      sudo rm -rf /tmp/nixcache

  - name: Check Conventional Commits
    # Ensure that the PR title fits the conventional commits framework
    if: github.event_name == 'pull_request'
    shell: bash
    env:
      TITLE: ${{ github.event.pull_request.title }}
    run: |
      set -ex
      echo "${TITLE}" | awk "/(^feat:)|(^fix:)|(^doc:)|(^perf:)|(^refactor:)|(^style:)|(^test:)|(^chore:)|(^revert:)|(^build:)/" | grep .

  - name: C++ Formatting
    shell: bash
    run: |
      set -ex
      nix develop --command clang-format --version
      find . -type f -regex '.*\.\(c\|cpp\|h\|hpp\|hui\)' -exec nix develop --command clang-format -i {} +
      git diff
      git diff --quiet

  - name: CMake Formatting
    shell: bash
    run: |
      set -ex
      nix develop --command cmake-format --version
      find . -type f -name CMakeLists.txt -exec nix develop --command cmake-format -i '{}' \;
      git diff
      git diff --quiet

  - name: QML Formatting
    shell: bash
    run: |
      set -ex
      nix develop --command qmlformat --version
      find . -type f -regex '.*\.qml' -exec nix develop --command qmlformat -inw 4 '{}' \;
      git diff
      git diff --quiet

  - name: Copyright Year
    shell: bash
    run: |
      set -ex
      # Find all occurances of "YYYY Team Dissolve and contributors" and replace YYYY with the current year
      find . -type f -not -path '.git/*' -exec sed -ri "s/[0-9]{4} (Team Dissolve and contributors)/$(date +%Y) \1/g" {} +
      # Show the diff to give an indication of the issues in the CI log
      git diff
      # Run quiet diff to fail the job if any changes were made (see man git-diff)
      git diff --quiet

  - name: Cpp Check
    shell: bash
    run: |
      set -ex
      MAX_ERRORS=3
      MAX_WARNINGS=1
      nix develop -L --command scripts/cppCheckTest.sh $MAX_ERRORS $MAX_WARNINGS
