#!/bin/bash

#-----------------------------------------------------------#
# Package Example Data - Must be run from the examples/ dir #
#-----------------------------------------------------------#

DISSOLVEVERSION=""

usage()
{
	echo "Usage: $0 [-v Dissolve version]"
	exit 1
}

# Parse options
while getopts ":v:" opt
do
	case "${opt}" in
		v)
			DISSOLVEVERSION=${OPTARG}
			echo "Dissolve version set to '${DISSOLVEVERSION}'"
			;;
		\?)
			usage
			;;
		*)
			usage
			;;
	esac
done

if [ "x$DISSOLVEVERSION" = "x" ]
then
	echo "Error: The code version must be set with -v (for naming purposes)."
	exit 1
fi

ARCHIVEDIR="Dissolve-${DISSOLVEVERSION}-ExampleData"
FILES=()

#-----------------------------------------------------------#
#                     Set File Targets                      #
#-----------------------------------------------------------#

FILES=( $(find ./ -mindepth 2 -type f -not -regex '.*/_.*') )

#-----------------------------------------------------------#
#                    Assemble Files                         #
#-----------------------------------------------------------#

mkdir ${ARCHIVEDIR}
for file in "${FILES[@]}"
do
  if [[file != "CMakeLists.txt"]]
  then
  	cp -v --parents "${file}" ${ARCHIVEDIR}
  fi
done

# Create ZIP
zip -9rv ${ARCHIVEDIR}.zip ${ARCHIVEDIR}

# Create tgz
tar zcvf ${ARCHIVEDIR}.tar.gz ${ARCHIVEDIR}

# Clean up
rm -rf ${ARCHIVEDIR}

# All done.

exit 0
