name: Package
description: Package OSX artifacts

runs:
  using: "composite"
  steps:

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ env.pythonVersion }}

  - name: Retrieve Qt Cache
    uses: actions/cache@v3
    with:
      key: osx-qt-${{ env.qtVersion }}
      path: ${{ runner.temp }}/qt

  - name: Download Raw Build Artifacts
    uses: actions/download-artifact@v3
    with:
      name: osx-build-artifacts-silicon
      path: ${{ github.workspace }}

  - name: Install Python Dependencies
    shell: bash
    run: |
      pip3 install --user dmgbuild biplist

  - name: Install Custom Dependencies
    shell: bash
    run: |
      set -ex
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-dmg
      chmod u+x ./prep-dmg

  - name: Prepare DMG Dirs
    shell: bash
    run: |
      set -ex
      Qt6_ROOT=${{ runner.temp }}/qt/${{ env.qtVersion }}/macos/
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Handle ANTLR & TBB & FTGL
      cp ./deploy/antlr4-cppruntime/lib/libantlr4-runtime.4.13.1.dylib /usr/local/lib/libantlr4-runtime.4.13.1.dylib
      cp ./deploy/antlr4-cppruntime/lib/libantlr4-runtime.dylib /usr/local/lib/libantlr4-runtime.dylib

      cp ./deploy/ftgl/libftgl.2.dylib /usr/local/lib/libftgl.2.dylib
      cp ./deploy/ftgl/libftgl.2.dylib /usr/local/lib/libftgl.2.1.3.dylib

      cp ./deploy/freetype/libfreetype.6 /usr/local/lib/libfreetype.6

      cp ./deploy/libpng/libpng16.16.dylib /usr/local/lib/libpng16.16.dylib

      for FILE in ./deploy/onetbb/lib/*.dylib; do
        FILENAME=$(basename $FILE)
        cp ./deploy/onetbb/lib/$FILENAME /usr/local/lib/$FILENAME
      done

      install_name_tool -add_rpath "@executable_path/../Frameworks/" build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      install_name_tool -add_rpath "/usr/local/lib" build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      install_name_tool -add_rpath "/opt/homebrew/lib" build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      ./prep-dmg -a Dissolve-GUI -v ${{ env.dissolveVersion }} -b build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p build/bin/dissolve-gui.app/Contents/Info.plist -L /opt/homebrew/lib

  - name: Create Disk Image
    shell: bash
    run: |
      set -ex
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Fix icon link
      sed -i -e "s/Dissolve.icns/Dissolve-GUI.icns/g" Dissolve-GUI-${dissolveVersion}/Dissolve-GUI.app/Contents/Info.plist

      # Create DMG
      dmgbuild -s ci/osx/dmgbuild-settings.py -D app=./Dissolve-GUI-${dissolveVersion}/Dissolve-GUI.app -D icon=./Dissolve-GUI-${dissolveVersion}/Dissolve-GUI.app/Contents/Resources/Dissolve-GUI.icns "Dissolve GUI" Dissolve-GUI-${dissolveVersion}.dmg

      # Collect artifacts
      mkdir packages
      mv Dissolve-GUI-${dissolveVersion}.dmg packages/

  - name: Upload Package Artifacts
    uses: actions/upload-artifact@v3
    with:
      name: packages
      path: ${{ github.workspace }}/packages
