// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Team Dissolve and contributors

#include "main/cli.h"
#include "CLI/CLI.hpp"
#include "base/messenger.h"
#include "main/version.h"
#include <CLI/App.hpp>
#include <CLI/Config.hpp>
#include <CLI/Formatter.hpp>

CLIOptions::CLIOptions() {}

// Parse CLI options
int CLIOptions::parse(const int args, char **argv, bool isGUI)
{
    // Create CLI object
    CLI::App app{std::format("Dissolve-{} version {}, Copyright (C) 2026 Team Dissolve and contributors.\n", Version::appType(),
                             Version::info())};
    // Add positionals
    auto inputFileOption = app.add_option("inputFile", inputFile_, "Input file to load")->check(CLI::ExistingFile);

    // Basic Control
    app.add_flag_callback(
           "-q,--quiet", []() { Messenger::setQuiet(true); },
           "Be quiet - don't output any messages whatsoever (output files are still written)")
        ->group("Basic Control");
    app.add_option("--seed", randomSeed_, "Random number seed to use (otherwise determined by system time)")
        ->group("Basic Control");
    app.add_flag_callback(
           "-v,--verbose", []() { Messenger::setVerbose(true); }, "Print lots of additional output, useful for debugging")
        ->group("Basic Control");
    app.add_flag("-m, --mermaid", exportMermaid_, "Export graph as a mermaid diagram and exit")->group("Basic Control");

    // Input Files
    app.add_flag("-i,--ignore-restart", ignoreRestartDirectory_, "Ignore restart directory (if it exists)")
        ->group("Input Files");
    app.add_option("--restart", restartDirectoryName_,
                   "Read restart directory specified instead of the default one (but still write to the default one)")
        ->group("Input Files")
        ->check(CLI::ExistingDirectory);
    if (!isGUI)
    {
        inputFileOption->required();
        app.add_option("node", node_, "Node to run")->required();

        app.add_option("-w,--write-input", writeInputFilename_,
                       "Write out the current simulation input to the file specified and then quit")
            ->group("Input Files");
        app.add_flag("--reload-after-write", writeInputAndReload_,
                     "Reload the input generated by --write-input and continue instead of quitting")
            ->group("Input Files");
    }

    // Output Files
    app.add_option("-f,--frequency", restartDirectoryFrequency_, "Frequency at which to write directory (default = 10)")
        ->group("Output Files");
    app.add_flag("-x,--no-restart-file", noRestartDirectory_, "Don't write restart directory at all")->group("Output Files");

    // Tweak formatting
    app.get_formatter()->label("TEXT:FILE", "<filename>");
    app.get_formatter()->label("TEXT:DIR", "<directory>");
    app.get_formatter()->label("INT", "<n>");

    // Parse the supplied options.
    // The CLI11_PARSE macro expands to a simple try/catch block, returning non-zero on error.
    // However, early exits from -h or --help return zero, and a successful parse does not return at all.
    // So, we return 1 on a "non-help" success to inform the calling function that it should proceed.
    CLI11_PARSE(app, args, argv);

    return CLIOptions::Success;
}

// Return input file to load
std::optional<std::filesystem::path> CLIOptions::inputFile() const { return inputFile_; }

// Return the node to run
std::string CLIOptions::node() const { return node_; }

// Return frequency at which to write restart file
int CLIOptions::restartDirectoryFrequency() const { return restartDirectoryFrequency_; }

// Return seed for random number generator
std::optional<int> CLIOptions::randomSeed() const { return randomSeed_; }

// Return restart file to load, overriding default
std::optional<std::filesystem::path> CLIOptions::restartDirectoryName() const { return restartDirectoryName_; }

// Return new input file to write (after reading supplied file)
std::optional<std::filesystem::path> CLIOptions::writeInputFilename() const { return writeInputFilename_; }

// Return whether to reload the file written to writeInputFilename_ and continue
bool CLIOptions::writeInputAndReload() const { return writeInputAndReload_; }

// Return whether to ignore restart directory if it exists
bool CLIOptions::ignoreRestartDirectory() const { return ignoreRestartDirectory_; }

// Return whether to prevent writing of the restart directory
bool CLIOptions::noRestartDirectory() const { return noRestartDirectory_; }

// Return whether to simply export the graph as mermaid and quit
bool CLIOptions::exportMermaid() const { return exportMermaid_; }
