name: Package
description: Package OSX artifacts

inputs:
  currentVersion:
    type: string
    required: true
  qtVersion:
    type: string
    required: true

runs:
  using: "composite"
  steps:

  - name: Download Qt Artifact
    uses: actions/download-artifact@v4
    with:
      name: osx-${{ runner.arch }}-qt
      path: ${{ runner.temp }}/qt

  - name: Prepare Qt
    shell: bash
    run: |
      set -ex
      ls -R  ${{ runner.temp }}/qt/${{ inputs.qtVersion }}/macos
      chmod -R u+x ${{ runner.temp }}/qt/${{ inputs.qtVersion }}/macos/bin/*
      chmod -R u+x ${{ runner.temp }}/qt/${{ inputs.qtVersion }}/macos/libexec/*

  - name: Download Raw Build Artifacts
    uses: actions/download-artifact@v4
    with:
      name: osx-${{ runner.arch }}-build-artifacts
      path: ${{ github.workspace }}/build

  - name: Install Dependencies
    shell: bash
    run: |
      set -ex
      brew update-reset
      brew install gsl
      pip3 install dmgbuild biplist --break-system-packages
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-dmg
      chmod u+x ./prep-dmg

  - name: Prepare DMG Dirs
    shell: bash
    run: |
      set -ex
      Qt6_ROOT=${{ runner.temp }}/qt/${{ inputs.qtVersion }}/macos/
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Set variables
      appName=Dissolve-GUI-QML-${{ runner.arch }}
      appDirName=${appName}.app
      packageName=Dissolve-GUI-QML-${{ runner.arch }}-${{ inputs.currentVersion }}

      # Prepare the dmg file content
      ./prep-dmg -a Dissolve-GUI-QML-${{ runner.arch }} -v ${{ inputs.currentVersion }} -b build/bin/dissolve-gui-qml.app/Contents/MacOS/dissolve-gui-qml -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p build/bin/dissolve-gui-qml.app/Contents/Info.plist -q src/gui/qml

      # Copy dependencies into Frameworks folder in app bundle
      cp -v ./build/antlr4-cppruntime/lib/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/
      cp -v ./build/onetbb/lib/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/
      cp -v ./build/gsl/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/

  - name: Create Disk Image
    shell: bash
    run: |
      set -ex
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Set variables
      appName=Dissolve-GUI-QML-${{ runner.arch }}
      appDirName=${appName}.app
      packageName=Dissolve-GUI-${{ runner.arch }}-${{ inputs.currentVersion }}
      dmgName=Dissolve-GUI-${{ inputs.currentVersion }}-${{ runner.arch }}

      # Fix icon name in plist
      sed -i -e "s/Dissolve.icns/${appName}.icns/g" ${packageName}/${appDirName}/Contents/Info.plist

      # Create DMG
      dmgbuild -s ci/osx/dmgbuild-settings.py -D app=./${packageName}/${appDirName} -D icon=./Dissolve-GUI-${{ inputs.currentVersion }}/${appDirName}/Contents/Resources/${appName}.icns "Dissolve GUI" ${dmgName}.dmg

      # Collect artifacts
      mkdir packages
      mv ${dmgName}.dmg packages/

  - name: Upload Package Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: packages-osx-${{ runner.arch }}
      path: ${{ github.workspace }}/packages
