name: Package
description: Package OSX artifacts

runs:
  using: "composite"
  steps:

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ env.pythonVersion }}

  - name: Retrieve Qt Cache
    uses: actions/cache@v3
    with:
      key: osx-qt-${{ env.qtVersion }}
      path: ${{ runner.temp }}/qt

  - name: Download Raw Intel Build Artifacts
    uses: actions/download-artifact@v3
    with:
      name: osx-build-artifacts-x86_64
      path: ${{ github.workspace }}/intel

  - name: Download Raw Silicon Build Artifacts
    uses: actions/download-artifact@v3
    with:
      name: osx-build-artifacts-arm64
      path: ${{ github.workspace }}/silicon

  - name: Install Python Dependencies
    shell: bash
    run: |
      pip3 install --user dmgbuild biplist

  - name: Install Custom Dependencies
    shell: bash
    run: |
      set -ex
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-dmg
      chmod u+x ./prep-dmg

  - name: Prepare DMG Dirs
    shell: bash
    run: |
      set -ex
      Qt6_ROOT=${{ runner.temp }}/qt/${{ env.qtVersion }}/macos/
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Handle ANTLR
      cp ./deploy/antlr4-cppruntime/lib/*.dylib /usr/local/lib/
      cp ./deploy/tbb/lib/*.dylib /usr/local/lib/

      # Intel

      install_name_tool -add_rpath "@executable_path/../Frameworks/" intel/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      install_name_tool -add_rpath "/usr/local/lib" intel/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      ./prep-dmg -a Dissolve-GUI-Intel -v ${{ env.dissolveVersion }} -b intel/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p intel/build/bin/dissolve-gui.app/Contents/Info.plist -L /usr/local/lib

      # Silicon

      install_name_tool -add_rpath "@executable_path/../Frameworks/" silicon/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      install_name_tool -add_rpath "/usr/local/lib" silicon/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui
      ./prep-dmg -a Dissolve-GUI-Silicon -v ${{ env.dissolveVersion }} -b silicon/build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p silicon/build/bin/dissolve-gui.app/Contents/Info.plist -L /usr/local/lib

  - name: Create Disk Image
    shell: bash
    run: |
      set -ex
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Fix icon link
      sed -i -e "s/Dissolve.icns/Dissolve-GUI.icns/g" Dissolve-GUI-Intel-${dissolveVersion}/Dissolve-GUI.app/Contents/Info.plist
      sed -i -e "s/Dissolve.icns/Dissolve-GUI.icns/g" Dissolve-GUI-Silicon-${dissolveVersion}/Dissolve-GUI.app/Contents/Info.plist

      # Merge binaries into the Silicon bundle
      lipo -create -output Dissolve-GUI-Silicon-${dissolveVersion}/Dissolve-GUI.app/Contents/MacOS/dissolve-gui Dissolve-GUI-Intel-${dissolveVersion}/Dissolve-GUI.app/Contents/MacOS/dissolve-gui Dissolve-GUI-Silicon-${dissolveVersion}/Dissolve-GUI.app/Contents/MacOS/dissolve-gui

      # Create DMG
      dmgbuild -s ci/osx/dmgbuild-settings.py -D app=./Dissolve-GUI-Silicon-${dissolveVersion}/Dissolve-GUI.app -D icon=./Dissolve-GUI-Silicon-${dissolveVersion}/Dissolve-GUI.app/Contents/Resources/Dissolve-GUI.icns "Dissolve GUI" Dissolve-GUI-${dissolveVersion}.dmg

      # Collect artifacts
      mkdir packages
      mv Dissolve-GUI-${dissolveVersion}.dmg packages/

  - name: Upload Package Artifacts
    uses: actions/upload-artifact@v3
    with:
      name: packages
      path: ${{ github.workspace }}/packages
