name: Package
description: Package OSX artifacts

runs:
  using: "composite"
  steps:

  - name: Retrieve Qt Cache
    uses: actions/cache@v3
    with:
      key: osx-qt-${{ env.qtVersion }}
      path: ${{ runner.temp }}/qt

  - name: Download Raw Build Artifacts
    uses: actions/download-artifact@v4
    with:
      name: osx-${{ runner.arch }}-build-artifacts
      path: ${{ github.workspace }}/build

  - name: Install Python Dependencies
    shell: bash
    run: |
      pip3 install --user dmgbuild biplist

  - name: Install Custom Dependencies
    shell: bash
    run: |
      set -ex
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-dmg
      chmod u+x ./prep-dmg

  - name: Prepare DMG Dirs
    shell: bash
    run: |
      set -ex
      Qt6_ROOT=${{ runner.temp }}/qt/${{ env.qtVersion }}/macos/
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      # Add rpath to packaged Frameworks
      install_name_tool -add_rpath "@executable_path/../Frameworks/" build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui

      # Add homebrew rpath - DO WE STILL NEED THIS?
      #install_name_tool -add_rpath "/opt/homebrew/lib" build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui

      ./prep-dmg -a Dissolve-GUI-${{ runner.arch }} -v ${{ env.dissolveVersion }} -b build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p build/bin/dissolve-gui.app/Contents/Info.plist

      appDirName=Dissolve-GUI-${{ runner.arch }}.app
      packageName=Dissolve-GUI-${{ runner.arch }}-${{ env.dissolveVersion }}

      # Copy dependencies into Frameworks folder in app bundle
      cp -v ./build/antlr4-cppruntime/lib/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/
      cp -v ./build/ftgl/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/
      cp -v ./build/onetbb/lib/*.dylib ${packageName}/${appDirName}/Contents/Frameworks/

  - name: Create Disk Image
    shell: bash
    run: |
      set -ex
      export PATH="$(python3 -m site --user-base)/bin:$PATH"

      appDirName=Dissolve-GUI-${{ runner.arch }}.app
      packageName=Dissolve-GUI-${{ runner.arch }}-${{ env.dissolveVersion }}

      # Fix icon link
      sed -i -e "s/Dissolve.icns/Dissolve-GUI.icns/g" ${packageName}/${appDirName}/Contents/Info.plist

      # Create DMG
      dmgbuild -s ci/osx/dmgbuild-settings.py -D app=./${packageName}/${appDirName} -D icon=./Dissolve-GUI-${{ env.dissolveVersion }}/${appDirName}/Contents/Resources/Dissolve-GUI.icns "Dissolve GUI" ${packageName}.dmg

      # Collect artifacts
      mkdir packages
      mv ${packageName}.dmg packages/

  - name: Upload Package Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: packages-osx-${{ runner.arch }}
      path: ${{ github.workspace }}/packages
