name: Develop MSVC
description: Set up Dissolve CLI and GUI Visual Studio dev environment.

inputs:
    publishType:
        type: choice
        default: 'none'
        options:
            - none
            - continuous
            - release
            - legacy
        
runs:
    using: "composite"
    steps:

    - name: 'Run developer powershell script'
      shell: pwsh
      run: ./develop.ps1 -systemqt

    - name: 'Find dependencies'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}

        if (Test-Path "./dependencies") {
          Write-Host "Found dependencies."
        } else {
          Write-Host "Could NOT find dependencies."
          exit 1
        }
    
    - name: 'Find CMake user presets'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}

        if (Test-Path "CMakeUserPresets.json") {
          Write-Host "Found CMakeUserPresets.json - Content: "
          Get-Content "CMakeUserPresets.json" | ConvertFrom-Json | ConvertTo-Json -Depth 10
        } else {
          Write-Host "Could NOT find CMakeUserPresets.json"
          exit 1
        }

    - name: 'Configure Dissolve for Visual Studio using CMake'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}
        #cmake --preset GUI-Debug-MSVC 
        cmake --build build --config CLI-Debug-MSVC

#    - name: 'Build Dissolve for Visual Studio using CMake'
#      shell: pwsh
#      run: |
#        Set-Location ${{ github.workspace }}
#        cmake --build ./out/build