name: Develop MSVC
description: Set up Dissolve CLI and GUI Visual Studio dev environment.

inputs:
    publishType:
        type: choice
        default: 'none'
        options:
            - none
            - continuous
            - release
            - legacy
        
runs:
    using: "composite"
    steps:

    - name: 'Set up MSVC toolchain'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
      
    - name: 'Install dependencies'
      shell: pwsh
      with:    
        key: windows-qt-${{ env.qtVersion }}
      run: | 
        Set-Location ${{ github.workspace }}

        # Run installation script
        ./develop.ps1 -systemqt
        
        # Check paths are correct
        $systemPath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::Machine)
        Write-Output "$systemPath"
        $qt6Path = "dissolve\dependencies\qt\qt\${{ env.qtVersion }}\msvc2019_64"
        $pythonEnvPath = "dissolve\dependencies\msvc-env\Scripts"

        if ($systemPath -notlike "*$qt6Path*") {
            Write-Output "Qt6 not found in PATH"
            exit 1
        }

        if ($systemPath -notlike "*$pythonEnvPath*") {
            Write-Output "Python env not found in PATH"
            exit 1
        }

#    - name: 'Configure and build with CMake'
#      shell: bash
#      run: |
#        export PATH="${{ github.workspace }}\msvc-env\Scripts;$PATH"
#        cmake --preset CLI-Debug-MSVC
#        cmake --build build