name: Develop MSVC
description: Set up Dissolve CLI and GUI Visual Studio dev environment.

inputs:
    publishType:
        type: choice
        default: 'none'
        options:
            - none
            - continuous
            - release
            - legacy
        
runs:
    using: "composite"
    steps:

    - name: 'Run developer powershell script'
      shell: pwsh
      run: Set-Location ${{ github.workspace }}

    - name: 'Run developer powershell script'
      shell: pwsh
      run: ./develop.ps1

    - name: 'Find dependencies'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}

        if (Test-Path "./dependencies") {
          Write-Host "Found dependencies."
        } else {
          Write-Host "Could NOT find dependencies."
          exit 1
        }
    
    - name: 'Find CMake user presets'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}

        if (Test-Path "CMakeUserPresets.json") {
          Write-Host "Found CMakeUserPresets.json - Content: "
          Get-Content "CMakeUserPresets.json" | ConvertFrom-Json | ConvertTo-Json -Depth 10
        } else {
          Write-Host "Could NOT find CMakeUserPresets.json"
          exit 1
        }

    - name: 'Configure Dissolve for Visual Studio using CMake'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}
        $msvcCompiler = "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe"
        cmake --preset GUI-Debug-MSVC -DCMAKE_CXX_COMPILER=$msvcCompiler -DCMAKE_C_COMPILER=$msvcCompiler 

    - name: 'Build Dissolve for Visual Studio using CMake'
      shell: pwsh
      run: |
        Set-Location ${{ github.workspace }}
        cmake --build ./out/build