add_library(
  math
  combinations.cpp
  combinations.h
  cuboid.cpp
  cuboid.h
  data1DBase.h
  data1D.cpp
  data1D.h
  data2DBase.h
  data2D.cpp
  data2D.h
  data3DBase.h
  data3D.cpp
  data3D.h
  dataBase.h
  derivative.cpp
  derivative.h
  doubleExp.cpp
  doubleExp.h
  error.cpp
  error.h
  filters.cpp
  filters.h
  ft.cpp
  ft.h
  function1D.cpp
  function1D.h
  functionSpace.h
  gaussFit.cpp
  gaussFit.h
  gj.cpp
  gj.h
  histogram1D.cpp
  histogram1D.h
  histogram2D.cpp
  histogram2D.h
  histogram3D.cpp
  histogram3D.h
  history.h
  integerHistogram1D.cpp
  integerHistogram1D.h
  integrator.cpp
  integrator.h
  interpolator.cpp
  interpolator.h
  limitsFunc.h
  mathFunc.cpp
  mathFunc.h
  matrix3.cpp
  matrix3.h
  matrix4.cpp
  matrix4.h
  mc.cpp
  mc.h
  peaks.cpp
  peaks.h
  poissonFit.cpp
  poissonFit.h
  polynomial.cpp
  polynomial.h
  praxis.cpp
  praxis.h
  range.cpp
  range.h
  rangedVector3.cpp
  rangedVector3.h
  regression.cpp
  regression.h
  sampledData1D.cpp
  sampledData1D.h
  sampledDouble.cpp
  sampledDouble.h
  sampledVector.cpp
  sampledVector.h
  svd.cpp
  svd.h
  transformer.cpp
  transformer.h
  vector3.cpp
  vector3.h
  vector3i.cpp
  vector3i.h
  vector4.cpp
  vector4.h
  windowFunction.cpp
  windowFunction.h
)

target_include_directories(math PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(math PRIVATE base)
