// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2021 Team Dissolve and contributors

// General include for all KeywordWidget types
#include "gui/keywordwidgets/atomtypevector.h"
#include "gui/keywordwidgets/base.h"
#include "gui/keywordwidgets/bool.hui"
#include "gui/keywordwidgets/configuration.hui"
#include "gui/keywordwidgets/configurationvector.h"
#include "gui/keywordwidgets/double.hui"
#include "gui/keywordwidgets/dropwidget.hui"
#include "gui/keywordwidgets/enumoptions.hui"
#include "gui/keywordwidgets/expressionvariablevector.h"
#include "gui/keywordwidgets/fileandformat.h"
#include "gui/keywordwidgets/function1d.h"
#include "gui/keywordwidgets/integer.hui"
#include "gui/keywordwidgets/isotopologueset.h"
#include "gui/keywordwidgets/module.h"
#include "gui/keywordwidgets/modulevector.h"
#include "gui/keywordwidgets/node.h"
#include "gui/keywordwidgets/nodeandinteger.h"
#include "gui/keywordwidgets/nodevalue.h"
#include "gui/keywordwidgets/nodevalueenumoptions.h"
#include "gui/keywordwidgets/nodevector.h"
#include "gui/keywordwidgets/optionaldouble.hui"
#include "gui/keywordwidgets/range.h"
#include "gui/keywordwidgets/species.hui"
#include "gui/keywordwidgets/speciessite.h"
#include "gui/keywordwidgets/speciessitevector.h"
#include "gui/keywordwidgets/speciesvector.h"
#include "gui/keywordwidgets/stdstring.hui"
#include "gui/keywordwidgets/vec3double.h"
#include "gui/keywordwidgets/vec3integer.h"
#include "gui/keywordwidgets/vec3nodevalue.h"
