name: Package Linux

inputs:
  target:
    default: "dissolve"
  singularityTarget:
    default: "singularity"


runs:
  using: "composite"
  steps:

  - name: Download Raw Build Artifacts
    uses: actions/download-artifact@v3
    with:
      name: linux-build-artifacts-${{ inputs.target }}
      path: ${{ github.workspace }}/packages
      retention-days: 1

  - name: Install nix
    uses: "./.github/workflows/get-nix"
    with:
      target: ${{ inputs.target }}

  - name: Package Singularity
    shell: bash
    run: |
      set -ex

      nix build -L .#${{ inputs.singularityTarget }}

      mkdir -p packages
      cp result packages/${{ inputs.target }}-${{ env.dissolveVersion }}}.sif

  - name: Upload Package Artifacts
    uses: actions/upload-artifact@v3
    with:
      name: packages
      path: ${{ github.workspace }}/packages
