trigger:
  branches:
    include:
      - release/*

pr: none

stages:
  - template: templates/code-quality-checks.yml

  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux'
        displayName: 'Ubuntu, Threads, CLI/GUI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
            parameters:
              extraflags: '-DBUILD_SYSTEM_TESTS:bool=true -DBUILD_UNIT_TESTS:bool=true'
          - template: templates/package-linux.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "build/"
              ArtifactName: 'linux-tests'
            displayName: 'Publish Threaded Test Artifacts'
      - job: 'linux_mpi'
        displayName: 'Ubuntu, MPI, CLI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux-mpi.yml
            parameters:
              extraflags: '-DBUILD_SYSTEM_TESTS:bool=true'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "build/"
              ArtifactName: 'linux-tests-mpi'
            displayName: 'Publish MPI Test Artifacts'
      - job: 'osx'
        displayName: 'OSX, Threads, CLI/GUI'
        timeoutInMinutes: 120
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
          - template: templates/package-osx.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows'
        displayName: 'Windows, Threads, CLI/GUI'
        timeoutInMinutes: 120
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
          - template: templates/package-windows.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'

  # Run Tests
  - stage: 'tests'
    displayName: 'Testing'
    jobs:
      - template: templates/tests.yml
        parameters:
          serial: false

  # Create Release
  - template: templates/create-release.yml
