trigger:
  branches:
    include:
      - release/*

pr: none

stages:
  - template: templates/code-quality-checks.yml

  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - template: templates/build-linux-releases.yml
      - job: 'osx'
        condition: eq(1,0)
        displayName: 'OSX, Threads, CLI/GUI'
        timeoutInMinutes: 120
        pool:
          vmImage: 'macOS-10.15'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
          - template: templates/package-osx.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows'
        condition: eq(1,0)
        displayName: 'Windows, Threads, CLI/GUI'
        timeoutInMinutes: 150
        pool:
          vmImage: 'windows-2022'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
          - template: templates/package-windows.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'
      - job: "test_linux_mpi"
        condition: eq(1,0)
        displayName: "Testing MPI, CLI"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve-mpi"
      - job: "test_linux_gui"
        condition: eq(1,0)
        timeoutInMinutes: 120
        displayName: "Testing GUI"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve"
      - job: "test_linux_threadless"
        condition: eq(1,0)
        displayName: "Testing Threadless"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve-threadless"
  - template: templates/package-linux.yml

  # Create Release
  - stage: 'release'
    displayName: 'Create Release'
    condition: eq(1,0)
    jobs:
      - template: templates/create-release.yml
