trigger:
  branches:
    include:
      - release/*

pr: none

stages:
  - template: templates/code-quality-checks.yml

  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux'
        displayName: 'Ubuntu, Threads, CLI/GUI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
            parameters:
              export: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "docker/"
              ArtifactName: "linux-gui-docker"
            displayName: "Publish Linux CLI Docker"
      - job: 'linux_mpi'
        displayName: 'Ubuntu, MPI, CLI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux-mpi.yml
            parameters:
              export: true
              package: "dissolve-mpi"
              docker: "docker-mpi"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: "mpi-artifacts"
            displayName: "Publish MPI Artifacts"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "docker/"
              ArtifactName: "mpi-docker"
            displayName: "Publish MPI Docker"
      - job: 'osx'
        displayName: 'OSX, Threads, CLI/GUI'
        timeoutInMinutes: 120
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
          - template: templates/package-osx.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows'
        displayName: 'Windows, Threads, CLI/GUI'
        timeoutInMinutes: 120
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
          - template: templates/package-windows.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'
      - job: "test_linux_mpi"
        displayName: "Testing MPI, CLI"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve-mpi"
      - job: "test_linux_gui"
        displayName: "Testing GUI"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve"
      - job: "test_linux_threadless"
        displayName: "Testing Threadless"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
            parameters:
              package: "checks.x86_64-linux.dissolve-threadless"

  # Create Release
  - stage: 'release'
    displayName: 'Create Release'
    condition: not(endsWith(variables['Build.SourceBranch'], 'pre'))
    jobs:
      - template: templates/create-release.yml
