trigger:
  branches:
    include:
      - release/*

pr: none

stages:
  - template: templates/code-quality-checks.yml

  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux_serialgui'
        displayName: 'Build Linux (Serial/GUI, ubuntu-18.04)'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux-serial-gui.yml
            parameters:
              extraflags: '-DBUILD_TESTS:bool=true'
              ppa: 'beineri/opt-qt-5.13.2-bionic'
              qtver: 513
          - template: templates/package-linux-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "build/"
              ArtifactName: 'linux-tests-serial'
            displayName: 'Publish Serial Test Artifacts'
      - job: 'linux_parallel'
        displayName: 'Build Linux (Parallel, ubuntu-18.04)'
        pool:
          vmImage: 'ubuntu-18.04' 
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux-parallel.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "build/"
              ArtifactName: 'linux-tests-parallel'
            displayName: 'Publish Parallel Test Artifacts'
      - job: 'osx_serialgui'
        displayName: 'Build OSX (Serial/GUI, macos-latest)'
        timeoutInMinutes: 120
        pool:
          vmImage: 'macos-latest' 
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx-serial-gui.yml
          - template: templates/package-osx-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows_serialgui'
        displayName: 'Build Windows (Serial/GUI, windows-latest)'
        timeoutInMinutes: 120
        pool:
          vmImage: 'windows-latest' 
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows-serial-gui.yml
          - template: templates/package-windows-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'

  # Run System Tests
  - stage: 'system_tests_serial'
    displayName: 'System Tests (Serial)'
    jobs:
      - template: templates/system-tests.yml
  - stage: 'system_tests_parallel'
    displayName: 'System Tests (Parallel)'
    jobs:
      - template: templates/system-tests.yml
        parameters:
          parallel: true

  # Create Release
  - template: templates/create-release.yml
