trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - web/*
    - .azure-pipelines/templates/build-web.yml
    exclude:
    - /

pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    include:
    - web/*
    - .azure-pipelines/templates/build-web.yml
    exclude:
    - /

# Only push changes to server if we are running on develop (i.e. the continuous build)
stages:
  - stage: 'web'
    displayName: 'Website'
    jobs:
      - job: 'buildweb'
        displayName: 'Update Web'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: templates/build-web.yml
            parameters:
              ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
                deploy: true
