name: MSVC
description: MSVC

on:
  pull_request:
    branches:
    - '*'
    paths:
    - 'develop.ps1'

jobs:

  MsvcDev:
    needs: [Checkout]
    uses: "./.github/workflows/visual_studio"
    with:
      qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
      antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
