name: Publishing

on:
  workflow_call:
    inputs:
      publishType:
        required: true
        type: string
        description: "Publishing type"
      releaseName:
        type: string
        description: "Name of the release as it will appear on GitHub"
      releaseBody:
        type: string
        default: ''
        description: "Body text of the release as it will appear on GitHub"
      releaseBodyFile:
        type: string
        default: ''
        description: "Body file to use for body text, used in preference to releaseBody if provided"
      releaseTag:
        type: string
        default: ''
        description: "Existing tag which the release will be associated to on GitHub"
    secrets:
      HARBOR_USER:
        description: "Username for Harbor access"
      HARBOR_SECRET:
        description: "Key for Harbor access"

jobs:

  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: "./.github/workflows/setup"

    - name: Set Short Hash
      uses: "./.github/workflows/set-short-hash"

    - name: Publish
      uses: "./.github/workflows/publish"
      with:
        publishType: ${{ inputs.publishType }}
        releaseTag: ${{ inputs.releaseTag }}
        releaseName: ${{ inputs.releaseName }}
        releaseBody: ${{ inputs.releaseBody }}
        releaseBodyFile: ${{ inputs.releaseBodyFile }}
      env:
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
