name: Publishing

on:
  workflow_call:
    inputs:
      publishType:
        required: true
        type: string

jobs:

  QC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout_ref }}
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: Quality Control
      uses: "./.github/workflows/qc"
