name: Quality Control

on:
  workflow_call:

jobs:

  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Download Versioned Source
      uses: actions/download-artifact@v4
      with:
        name: versioned-source
    - name: Code Formatting
      uses: "./.github/workflows/qc"

  ConventionalCommits:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Download Versioned Source
      uses: actions/download-artifact@v4
      with:
        name: versioned-source
    - name: Conventional Commits
      shell: bash
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        set -ex
        echo "${TITLE}" | awk "/(^feat:)|(^fix:)|(^doc:)|(^perf:)|(^refactor:)|(^style:)|(^test:)|(^chore:)|(^revert:)|(^build:)/" | grep .

