name: benchmarks_ubuntu

on:
  # Trigger the workflow on push to the develop branch
  push:
    branches:
      - develop

env:
  BUILD_TYPE: Release

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install Prerequisites
          run: |
            sudo apt-get update -q
            sudo apt-get install antlr4 ninja-build python3-setuptools uuid uuid-dev
        - name: Install Conan
          run: |
            sudo pip3 install wheel
            sudo pip3 install conan
        - name: Build
          run: |
            mkdir build
            cd build
            conan install ../ -s compiler.libcxx=libstdc++11
            cmake -G "Ninja" -DBUILD_BENCHMARKS:bool=true -DBUILD_ANTLR_RUNTIME:bool=true ../
            ninja
        - name: Run benchmark
          run: ./build/bin/benchmarks --benchmark_format=json | tee benchmark_result.json
        - name: Store benchmark result
          uses: rhysd/github-action-benchmark@v1
          with:
              tool: 'googlecpp'
              output-file-path: benchmark_result.json
              github-token: ${{ secrets.GITHUB_TOKEN }}
              auto-push: true
              comment-on-alert: true
              alert-threshold: '200%'
              alert-comment-cc-users: '@disorderedmaterials/dissolve-devs'
