name: Generate Conan Caches

on:
  workflow_dispatch:
  push:
    branches:
    - 'develop'
    paths:
    - 'conanfile.txt'

jobs:

  Checkout:
    uses: "./.github/workflows/_checkout.yml"

  CacheConan:
    needs: [Checkout]
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        target: [dissolve-gui]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Download Source Tarfiles'
        uses: actions/download-artifact@v4
        with:
          name: source

      - name: 'Unpack Source'
        shell: bash
        run: tar -xvf dissolve-original-source.tar

      - name: "Build (Cache Only) (${{ matrix.os }})"
        uses: "./.github/workflows/build"
        with:
          target: ${{ matrix.target }}
          cacheOnly: true
          currentVersion: ${{ needs.Checkout.outputs.currentVersion }}
          qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
          msvcVersion: ${{ needs.Checkout.output.msvcVersion }}
          antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
          conanHash: ${{ needs.Checkout.outputs.conanHash }}

