name: Generate Conan Caches

on:
  workflow_dispatch:
  push:
    branches:
    - 'develop'
    paths:
    - 'conanfile.txt'

jobs:

  CacheConan:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        target: [dissolve-gui]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: "./.github/workflows/setup"
      - name: "Build (Cache Only) (${{ matrix.os }})"
        uses: "./.github/workflows/build"
        with:
          target: ${{ matrix.target }}
          cacheOnly: true

