name: Continuous

on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - '.github/workflows/benchmark.yml'
    - '.github/workflows/cacheConan.yml'
    - '.github/workflows/cacheNix.yml'
    - '.github/workflows/issues.yml'
    - '.github/workflows/pr.yml'
    - '.github/workflows/release.yml'
    - '.github/workflows/web**'
    - '.github/ISSUE_TEMPLATE/**'
    - 'web/**'
    - 'README.md'

jobs:

  Checkout:
    uses: "./.github/workflows/_checkout.yml"
    with:
      bump: true
      publishType: 'continuous'

  QC:
    needs: [Checkout]
    uses: "./.github/workflows/_qc.yml"

  BuildAndPackage:
    needs: [Checkout]
    uses: "./.github/workflows/_build_and_package.yml"

  Web:
    needs: [Checkout]
    uses: "./.github/workflows/website"
    with:
      publishType: 'continuous'
    env:
      SERVER_ID: ${{ secrets.SERVER_ID }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_DOCS_DIR: ${{ secrets.SERVER_DOCS_DIR }}
      SERVER_MAIN_DIR: ${{ secrets.SERVER_MAIN_DIR }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

  Publish:
    needs: [Checkout,BuildAndPackage,Web]
    uses: "./.github/workflows/_publishing.yml"
    with:
      publishType: 'continuous'
      releaseTag: 'continuous'
      releaseName: "Development Release ${{ needs.Checkout.outputs.currentVersion }} @ ${{ needs.Checkout.outputs.currentShortHash }}"
      releaseBodyFile: ./ChangeLog.md
    secrets: inherit
