name: Continuous

on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - '.github/workflows/benchmark.yml'
    - '.github/workflows/cacheConan.yml'
    - '.github/workflows/cacheNix.yml'
    - '.github/workflows/issues.yml'
    - '.github/workflows/pr.yml'
    - '.github/workflows/release.yml'
    - '.github/workflows/web**'
    - '.github/ISSUE_TEMPLATE/**'
    - 'web/**'
    - 'README.md'

jobs:

  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"

  Publish:
    needs: [BuildAndPackage]
    uses: "./.github/workflows/_publishing.yml"
    with:
      publishType: 'continuous'
