name: Detect Release
description: Runs on any merged release PR (actioned by prepare_release.yml)

on:
  pull_request:
    types:
      - closed

jobs:

  Checkout:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, '[Release]')
    uses: "./.github/workflows/_checkout.yml"
    secrets: inherit
    with:
      checkoutRef: ${{ github.event.pull_request.merge_commit_sha }}
      publishType: 'release'

  BuildAndPackage:
    needs: [Checkout]
    uses: "./.github/workflows/_build_and_package.yml"
    with:
      currentVersion: ${{ needs.Checkout.outputs.currentVersion }}
      qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
      antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
      conanHash: ${{ needs.Checkout.outputs.conanHash }}
      nixHash: ${{ needs.Checkout.outputs.nixHash }}

  Web:
    needs: [Checkout]
    uses: "./.github/workflows/_website.yml"
    with:
      publishType: 'release'
      displayMajorVersion: ${{ needs.Checkout.outputs.majorVersion }}
      displayMinorVersion: ${{ needs.Checkout.outputs.minorVersion }}
      hugoVersion: ${{ needs.Checkout.outputs.hugoVersion }}
    secrets: inherit

  Publish:
    needs: [Checkout,BuildAndPackage,Web]
    uses: "./.github/workflows/_publish.yml"
    with:
      publishType: 'release'
      releaseTag: ${{ needs.Checkout.outputs.currentVersion }}
      releaseName: "Release ${{ needs.Checkout.outputs.currentVersion }}"
      releaseBody: ${{ github.event.pull_request.body }}
      apptainerVersion: ${{ needs.Checkout.outputs.apptainerVersion }}
    secrets: inherit
