name: Detect Release
description: Runs on any merged release PR (actioned by prepare_release.yml)

on:
  pull_request:
    types:
      - closed

jobs:

  Checkout:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, '[Release]')
    uses: "./.github/workflows/_checkout.yml"
    secrets: inherit
    with:
      checkoutRef: ${{ github.event.pull_request.merge_commit_sha }}
      publishType: 'release'

  BuildAndPackage:
    needs: [Checkout]
    uses: "./.github/workflows/_build_and_package.yml"

  Web:
    needs: [Checkout]
    uses: "./.github/workflows/website"
    with:
      publishType: 'release'
    env:
      SERVER_ID: ${{ secrets.SERVER_ID }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_DOCS_DIR: ${{ secrets.SERVER_DOCS_DIR }}
      SERVER_MAIN_DIR: ${{ secrets.SERVER_MAIN_DIR }}

  Publish:
    needs: [Checkout,BuildAndPackage,Web]
    uses: "./.github/workflows/_publishing.yml"
    with:
      publishType: 'release'
      releaseTag: ${{ needs.Checkout.outputs.currentVersion }}
      releaseName: "Release ${{ needs.Checkout.outputs.currentVersion }}"
      releaseBody: ${{ github.event.pull_request.body }}
    secrets: inherit
