name: Legacy

on:
  push:
    tags:
    - 'legacy'

jobs:

  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"

  Publish:
    needs: [BuildAndPackage]
    uses: "./.github/workflows/_publishing.yml"
    with:
      publishType: 'legacy'
    secrets:
      HARBOR_USER: ${{ secrets.HARBOR_USER }}
      HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
