name: Test MSVC (Visual Studio 2022) Developer Build

on:
  workflow_call:
    inputs:
      qtVersion:
        type: string
        required: true
      antlrVersion:
        type: string
        required: true

jobs:

  MsvcDev:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: Checkout
        uses: actions/checkout@v4
      - name: Develop MSVC
        uses: "./.github/workflows/visual-studio"
        with:
          qtVersion: ${{ inputs.qtVersion }}
          antlrVersion: ${{ inputs.antlrVersion }}
          files: ${{ steps.changed-files.outputs.all_changed_files }}