name: Pull Request
description: Pull request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/cacheConan.yml'
    - '.github/workflows/cacheNix.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/issues.yml'
    - '.github/workflows/release.yml'
    - '.github/ISSUE_TEMPLATE/**'
    - 'README.md'

jobs:

  Checkout:
    uses: "./.github/workflows/_checkout.yml"
    with:
      checkoutRef: ${{ github.event.pull_request.head.sha }}

  QC:
    needs: [Checkout]
    uses: "./.github/workflows/_qc.yml"
    with:
      nixHash: ${{ needs.Checkout.outputs.nixHash }}

  BuildAndPackage:
    needs: [Checkout]
    uses: "./.github/workflows/_build_and_package.yml"
    with:
      benchmark: false
      currentVersion: ${{ needs.Checkout.outputs.currentVersion }}
      qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
      antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
      conanHash: ${{ needs.Checkout.outputs.conanHash }}
      nixHash: ${{ needs.Checkout.outputs.nixHash }}

  Web:
    needs: [Checkout]
    uses: "./.github/workflows/_website.yml"
    with:
      publishType: 'none'
      displayMajorVersion: ${{ needs.Checkout.outputs.majorVersion }}
      displayMinorVersion: ${{ needs.Checkout.outputs.minorVersion }}
      hugoVersion: ${{ needs.Checkout.outputs.hugoVersion }}
