name: Pull Request
description: Pull request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/benchmark.yml'
    - '.github/workflows/cacheConan.yml'
    - '.github/workflows/cacheNix.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/issues.yml'
    - '.github/workflows/release.yml'
    - '.github/workflows/web**'
    - '.github/ISSUE_TEMPLATE/**'
    - 'web/**'
    - 'README.md'

jobs:

  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"
    with:
      checkoutRef: ${{ github.event.pull_request.head.sha }}
