name: Recreate Release
description: A purely workflow dispatch action that re-releases a version based on a specific commit SHA pointing to a "[Release]"-prefixed merge commit.

on:
  workflow_dispatch:
    inputs:
      cacheOnly:
        type: boolean
        default: false
      releaseRef:
        type: string
        required: true
        default: ""

jobs:

  AssertRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkoutRef }}
          fetch-depth: 0

      - name: Confirm Release Prefix
        shell: bash
        run: |
          set -ex
          message=$(git log -1 --pretty=%B | head -n 1)
          if $(echo $message | head -n 1 | grep -q "\[Release\]")
          then
            echo "Found a valid [Release] tag: $message"
          else
            echo "::error::SHA ${{ inputs.releaseRef }} does not appear to be a release."
            echo "::error::Commit message is: $message"
            exit 1
          fi

  Checkout:
    needs: [AssertRelease]
    uses: "./.github/workflows/_checkout.yml"
    secrets: inherit
    with:
      checkoutRef: ${{ github.event.pull_request.merge_commit_sha }}
      publishType: 'release'

  BuildAndPackage:
    needs: [Checkout]
    uses: "./.github/workflows/_build_and_package.yml"
    with:
      currentVersion: ${{ needs.Checkout.outputs.currentVersion }}
      qtVersion: ${{ needs.Checkout.outputs.qtVersion }}
      antlrVersion: ${{ needs.Checkout.outputs.antlrVersion }}
      conanHash: ${{ needs.Checkout.outputs.conanHash }}
      nixHash: ${{ needs.Checkout.outputs.nixHash }}

  Web:
    needs: [Checkout]
    uses: "./.github/workflows/_website.yml"
    with:
      publishType: 'release'
      displayMajorVersion: ${{ needs.Checkout.outputs.currentVersionMajor }}
      displayMinorVersion: ${{ needs.Checkout.outputs.currentVersionMinor }}
      hugoVersion: ${{ needs.Checkout.outputs.hugoVersion }}
    secrets: inherit

  Publish:
    needs: [Checkout,BuildAndPackage,Web]
    uses: "./.github/workflows/_publish.yml"
    with:
      publishType: 'release'
      currentVersion: ${{ needs.Checkout.outputs.currentVersion }}
      releaseTag: ${{ needs.Checkout.outputs.currentVersion }}
      releaseName: "Release ${{ needs.Checkout.outputs.currentVersion }}"
      releaseBody: ${{ github.event.pull_request.body }}
      apptainerVersion: ${{ needs.Checkout.outputs.apptainerVersion }}
    secrets: inherit
