name: Website Build

on:
  pull_request:
    branches:
    - '*'
    paths:
    - '.github/workflows/web**'
    - 'web/**'

  push:
    branches:
    - 'develop'
    - 'release/**'
    paths:
    - '.github/workflows/web**'
    - 'web/**'

jobs:

  BuildWeb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: "./.github/workflows/setup"

    - name: Build Website - Test Only
      if: ${{ github.event_name == 'pull_request' }}
      uses: "./.github/workflows/website"
      with:
        publishType: 'none'

    - name: Build and Publish Website (Development Version)
      if: ${{ github.ref_name == 'develop' }}
      uses: "./.github/workflows/website"
      with:
        publishType: 'continuous'
      env:
        SERVER_ID: ${{ secrets.SERVER_ID }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_DOCS_DIR: ${{ secrets.SERVER_DOCS_DIR }}
        SERVER_MAIN_DIR: ${{ secrets.SERVER_MAIN_DIR }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}

    - name: Build and Publish Website (Release Version)
      if: ${{ startsWith(github.ref_name, 'release') }}
      uses: "./.github/workflows/website"
      with:
        publishType: 'release'
      env:
        SERVER_ID: ${{ secrets.SERVER_ID }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_DOCS_DIR: ${{ secrets.SERVER_DOCS_DIR }}
        SERVER_MAIN_DIR: ${{ secrets.SERVER_MAIN_DIR }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}

    - name: Build and Publish Website (Legacy Version)
      if: ${{ github.ref_name == 'legacy' }}
      uses: "./.github/workflows/website"
      with:
        publishType: 'legacy'
      env:
        SERVER_ID: ${{ secrets.SERVER_ID }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_DOCS_DIR: ${{ secrets.SERVER_DOCS_DIR }}
        SERVER_MAIN_DIR: ${{ secrets.SERVER_MAIN_DIR }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
