name: Website Build

on:
  pull_request:
    branches:
    - '*'
    paths:
    - '.github/workflows/web.yml'
    - 'web/**'

  push:
    branches:
    - 'develop'
    paths:
    - '.github/workflows/web.yml'
    - 'web/**'

jobs:

  BuildWeb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Website
      uses: "./.github/workflows/website"
      with:
        deploy: ${{ false }}
      env:
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
        SERVER_ID: $${ secrets.SERVER_ID }}
        SERVER_KEY: $${ secrets.SERVER_KEY }}
        SERVER_USER: $${ secrets.SERVER_USER }}
