baseURL = "https://www.projectdissolve.com/"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

title = "Dissolve"
theme = "docsy"

enableGitInfo = true
enableInlineShortcodes = true
relativeURLs = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Downloads"
    url = "#downloads"
    weight = 2

  [[menu.main]]
    name = "Documentation"
    url = "docs/"
    weight = 3

  [[menu.main]]
    name = "Forum"
    url = "https://forum.projectdissolve.com"
    weight = 4

[params]
copyright = "Dr Tristan Youngs, Simona (2019-). Built using Hugo/Docsy."
releaseVersion = "0.6.1"
devVersion = "0.7.0"
devShortHash = ""
github_repo = "https://github.com/projectdissolve/dissolve"
github_subdir = "web"
github_branch = "develop"

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
# Enable to show the side bar menu in its compact state
sidebar_menu_compact = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Link Configuration
[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
 [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/projectdissolve/dissolve"
    icon = "fab fa-github"
        desc = "Development takes place here!"
